web-compile:
  sass:
    files:
      src/scss/goodenergy-book-theme.scss: goodenergy_book_theme/static/goodenergy-book-theme.[hash].css
    precision: 5
    sourcemap: false
    format: compressed
  js:
    files:
      src/js/goodenergy-book-theme.js: goodenergy_book_theme/static/goodenergy-book-theme.[hash].js
  jinja:
    files:
      src/jinja/theme.conf.j2: goodenergy_book_theme/theme.conf
